// Generated by Wrangler on Wed Jul 31 2024 13:54:20 GMT+0800 (中国标准时间)
// by running `wrangler types`

interface Env {
	// Environment secrets
	SIGN_SECRET: string
	// Environment variables
	VERSION: string
	SERVICE_NAME: string
	DOMAINS: string[]
	FORBID_HTML: true
}
