name               = "mirrors"
main               = "src/index.ts"
compatibility_date = "2024-07-25"

# Development delpoyment
[env.development]
name = "mirrors"

[env.development.vars]
VERSION = "2.1.0"
SERVICE_NAME = "cf-worker-mirrors"
DOMAINS = []
FORBID_HTML = true

# Production deployment
[env.production]
name = "mirrors"
minify = true

[env.production.vars]
VERSION = "2.1.0"
SERVICE_NAME = "cf-worker-mirrors"
DOMAINS = []
FORBID_HTML = true

